# =============================================================================
# Multi-Seed Experiment Configuration (多种子实验配置)
# =============================================================================
# 用于生成带阴影（标准差）的曲线，证明方法的稳定性
#
# Usage: 
#   python train.py -p hyperparams_multiseed.yaml -c baseline -o results/multiseed/baseline -n baseline
#   python train.py -p hyperparams_multiseed.yaml -c specnorm -o results/multiseed/specnorm -n specnorm
#   python train.py -p hyperparams_multiseed.yaml -c redo -o results/multiseed/redo -n redo
# =============================================================================

experiment:
  algo: ppo
  save_freq: 200
  
  conditions:
    baseline:
      model.specnorm: false
    specnorm:
      model.specnorm: true
    redo:
      model.redo_weight: 0.025
      model.redo_freq: 10
    layernorm:
      model.layernorm: true
  
  name: null
  num_sessions: 3  # 3个随机种子

environment:
  name: procgen
  task: coinrun_100
  shift_type: permute
  obs_type: conv64
  env_copies: 8

model:
  enc_type: null
  h_size: 256
  lr: 0.0005
  l2_norm: 0.00
  l2_init: 0.00
  w2_init: 0.00
  redo_weight: 0.00
  redo_freq: 10
  activation: relu
  layernorm: false
  specnorm: false
  adapt_info: ['none', null]

ppo_trainer:
  batch_size: 64
  buffer_size: 1024
  num_passes: 3
  ent_coef: 0.02
  gamma: 0.99
  lambda: 0.95
  clip_param: 0.2
  num_epochs: 3000
  shift_points: [1000, 2000]
  test_episodes: 30
  test_interval: 50
